name: Build and deploy Python package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Build
        working-directory: py-api
        run: |
          python3 -m pip install --upgrade build twine
          python3 -m build

      - name: Publish to public repository
        if: github.ref == 'refs/heads/main'
        working-directory: py-api
        run: |
          export TWINE_USERNAME=token
          export TWINE_PASSWORD={{ secrets.PYPI_TOKEN }}
          python3 -m twine upload --repository pypi dist/*
