name: Staging Workflow New

on:
  push:
    branches:
      - development
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  diff-check:
    runs-on: ubuntu-latest
    outputs:
      py-api-service-updated: ${{ steps.py-api-service-changed-files.outputs.any_changed }}
      ts-api-service-updated: ${{ steps.ts-api-service-changed-files.outputs.any_changed }}
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
  
    - name: Get py-api service changed files
      id: py-api-service-changed-files
      uses: tj-actions/changed-files@v42
      with:
        files: |
          py-api/**
      
    - name: Get ts-api service changed files
      id: ts-api-service-changed-files
      uses: tj-actions/changed-files@v42
      with:
        files: |
          ts-api/**
  
  pypi-build:
    runs-on: ubuntu-latest
    needs: diff-check
    if: |
      needs.diff-check.outputs.py-api-service-updated == 'true' ||
      needs.diff-check.outputs.py-api-service-updated == null

    steps:
    - name: Checkout Code
      uses: actions/checkout@main

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::208761073495:role/OneByZeroGithubActions
        aws-region: ap-southeast-1

    - name: Set up Python
      uses: actions/setup-python@v3
    
    - name: Build
      working-directory: py-api
      run: |
        python3 -m pip install --upgrade build twine
        python3 -m build
    
    - name: upload windows dist
      uses: actions/upload-artifact@v4
      with:
        name: py-release-dists
        path: py-api/dist

  pypi-internal:
    runs-on: ubuntu-latest
    needs: pypi-build
    permissions:
      contents: read
      id-token: write
    
    steps:  # downloading the build. Do the same step in npm build
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: py-release-dists
          path: py-api/dist
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::208761073495:role/OneByZeroGithubActions
          aws-region: ap-southeast-1

      - name: Publish to internal repository
        working-directory: py-api
        run: |
          aws codeartifact login --tool twine --repository pypi_test --domain onebyzero-internal --domain-owner 208761073495 --region us-east-1
          python3 -m pip install --upgrade build twine
          python3 -m twine upload --repository codeartifact dist/* --verbose
  
  pypi-external:
    runs-on: ubuntu-latest
    needs: pypi-build
    permissions:
      contents: read
      id-token: write
    
    steps:  # downloading the build. Do the same step in npm build
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: py-release-dists
          path: py-api/dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::208761073495:role/OneByZeroGithubActions
          aws-region: ap-southeast-1

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: py-api/dist

  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        working-directory: ts-api
        run:  |
          npm install
          npm ci
          npm run build

  publish-internal-npm:
    needs: npm-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::208761073495:role/OneByZeroGithubActions
          aws-region: ap-southeast-1

      - name: Publish to internal repository
        working-directory: ts-api
        run: |
          aws codeartifact login --tool npm --repository npm_test --domain onebyzero-internal --domain-owner 208761073495 --region us-east-1
          npm publish

  publish-external-npm:
    needs: npm-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Publish to external repo
        working-directory: ts-api
        run: |
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}